### ISSUE TITLE
Trigger Javascript function instead of navigating to a link?

### ISSUE THREAD

**Issue by supertwang** [mkg0/mkg-sidebar#2]
Hi Mehmet,

Is there a way to have one of your menu items trigger a javascript function call, instead of navigating to a new URL?  I tried using "javascript: MyFunction()" for the value of 'link' in the menu items definition, but it didn't seem to like that. (I'd like to use it in a single-page app).

Also, one visual issue I came across... when using the menu on the right side of the page, the animation looks strange, like the menu is sliding in moving right from the middle of the window, instead of sliding out of the right edge moving left.  I hope this helps.

Best,
Dave

**Comment by mkg0** [comment]
hi supertwang,

firstly thanks for your issue report, i fixed it.
then i added callback property for item. also it can trigger inline onClick attr but as you know assigning callback function is much better.

```js
function(e){
e.preventDefault();
console.log(this.link)
}
```
